### ISSUE TITLE
示例项目跑不起来

### ISSUE THREAD

**Issue by brightfuture** [JuniperPhoton/PageView.SwiftUI#1]
Xcode有报错
<img width="428" alt="Screenshot 2023-05-04 at 16 56 42" src="https://user-images.githubusercontent.com/5242312/236157709-e3783ecb-aaf0-43e0-a28d-6c1c78c01291.png">

**Comment by JuniperPhoton** [comment]
感谢反馈，我这边已经修复了，请重新拉一下代码试一下。

**Comment by brightfuture** [comment]
依然报错，报错信息和之前一样

**Comment by JuniperPhoton** [comment]
那么请检查下是否是通过打开 `PageViewSample.xcodeproj` 工程文件来编译运行的，注意这个是在 `/PageViewSample` 子目录下。我这边是能正常编译运行了的，如果还不行，可能需要你自行排查下了。

**Comment by brightfuture** [comment]
是的，那我再研究研究

**Comment by JuniperPhoton** [comment]
发现新 Clone 的时候确实有这个问题，我修了下，现在应该解决了：

https://github.com/JuniperPhoton/PageView.SwiftUI/pull/3
