### ISSUE TITLE
会有事件冲突

### ISSUE THREAD

**Issue by Monkey-X-Byte** [JuniperPhoton/PageView.SwiftUI#2]
let gesture = DragGesture(minimumDistance: .zero, coordinateSpace: .global)
            .onEnded { value in
                onGestureEnd(value: value)
            }
            .updating($dragTranslationX) { v, state, _ in
                state = v.translation.width
            }
            
            
特别是 配合 UIViewRepresentable 接入另外的View ，上面要是有 按钮事件，就被拦截了

**Comment by Monkey-X-Byte** [comment]
minimumDistance 使用默认的就行了 .zero 的话都拦截完了

**Comment by JuniperPhoton** [comment]
感谢反馈。

试了下确实如此，在 iOS 上如果设置  `minimumDistance: .zero` 的话，UIKit 的 UIButton 会无法响应点击（而 SwiftUI 上的 Button 则没问题）；在 macOS 上则没有问题。

写这个的时候设置 `minimumDistance` 为 0 目的是为了能让拖拽的时候能及时响应，而不是超过一定的划动距离再开始让 PageView 来横向划动；但实际情况下，只有 iOS 模拟器和 Mac 上有效（或者说鼠标下有效？），使用触控在 iPhone 或者 iPad 上依然没有效果。

我考虑下删掉这个参数。不过我的这个 PageView 其实不太适合跟 UIKit 和 AppKit 的很多带手势（特别是划动手势）View 配合用，SwiftUI 在也无法很好地解决跟这两者本身的手势冲突...

**Comment by JuniperPhoton** [comment]
https://github.com/JuniperPhoton/PageView.SwiftUI/pull/4
